configurations:
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkRatingTesting/
        - Sources/SparkRatingSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoMockable.stencil
    output: Sources/SparkRatingTesting/Generated/AutoMockable.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkRating]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkRatingTesting/
        - Sources/SparkRatingSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoMockTest.stencil
    output: Sources/SparkRatingTesting/Generated/AutoMockTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkRating]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkRatingTesting/
        - Sources/SparkRatingSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoPublisherTest.stencil
    output: Sources/SparkRatingTesting/Generated/AutoPublisherTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkRating]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkRatingTesting/
        - Sources/SparkRatingSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoViewModelStub.stencil
    output: Sources/SparkRatingTesting/Generated/AutoViewModelStub.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkRating]
